name: Continuous-Integration

on:
    pull_request:
        branches: [main]

env:
    DATABASE_URL: postgresql://postgres:cheese66cakes@localhost:5432/PetCo
    JWT_SECRET_ACCESS: c3631916090d54d31d4dd4d7a6ea7c025b2b28368b160a859f6e3468fb1bd688ed64c26505ef35a

jobs:
    testing-api:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:14-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: cheese66cakes
                    POSTGRES_DB: PetCo
                ports: 
                  - 5432:5432
                
                options: >-
                  --health-cmd="pg_isready -U postgres -d PetCo"
                  --health-interval=10s
                  --health-timeout=5s
                  --health-retries=5

        steps:
            - name: Checkout code into the runner
              uses: actions/checkout@v4

            - name: setup nodejs on the runner
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install npm packages
              run: npm ci

            - name: Wait for PostgreSQL to be ready
              run: |
                until pg_isready -h localhost -p 5432 -U postgres; do 
                  echo "$(date) - waiting for database to be ready"
                  sleep 5
                done
              env:
                PGPASSWORD: cheese66cakes

            - name: Run migration files against DB
              run: npx prisma migrate deploy

            - name: run the integration tests
              run: npm test
